repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
- repo: git://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.7
  hooks:
  - id: forbid-tabs
    exclude_types: [python, javascript, dtd, markdown, makefile]
    exclude: binary|\.bin$
- repo: git://github.com/kintoandar/pre-commit.git
  rev: v2.1.0
  hooks:
  - id: terraform_fmt
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  -   id: detect-aws-credentials
  -   id: detect-private-key
